make:
	g++ newton.cpp -lpthread -lX11 -std=c++14 -fopenmp

o:
	g++ newton.cpp -lpthread -lX11 -std=c++14 -fopenmp -01

oo:
	g++ newton.cpp -lpthread -lX11 -std=c++14 -fopenmp -O2

ooo:
	g++ newton.cpp -lpthread -lX11 -std=c++14 -fopenmp -O3
